Download right network file
bacpop/beebop_py pull request #21
Opened 2022-10-24 10:55 UTC by muppi1993

As already done for downloading the .graphml data for the network visualisation, the network zip download now translates the cluster to component number to find the right files.

2022-10-27 09:22 UTC, richfitz requested changes

2022-10-27 09:22 UTC, richfitz commented on tests/files/poppunk_output/test_network_zip/network/network_component_38.graphml
> +<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/
can you please add instructions for how these were generated into the tests/files/popppunk_output directory

2022-11-25 11:18 UTC, muppi1993 commented
Is it legitimate to use the code you want to test to generate files needed to test that code? Unfortunately I can't generate the graphml files via the command line, the only other option I see to create these files is to write a script that generates them just like the beebop code does.

2022-11-29 15:00 UTC, richfitz commented
yes, this is totally legit :)

2022-11-29 15:00 UTC, richfitz approved these changes

2022-11-29 15:00 UTC, merged